### ISSUE TITLE
Multi consumer GPU

### ISSUE THREAD

**Issue by Curlypla** [bghira/SimpleTuner#27]
Have you had results with 2x cards that have 24G of vram, would the batch size be the same as using 48G A6000?

**Comment by bghira** [comment]
i think it would not work, yet. would need to find a reliable way to distribute the layers of the model across devices.

this might come in the form of DeepSpeed Zero stage 3 or something.

at some point i might create a document that outlines the hardware requirements a bit better.

as it is now, the parallel training starts a complete copy of the U-net on both GPUs. this was tricky for a while before adding precomputation of embeds/latents, because the VAE would push the GPU use around 57GB or beyond.

it's just "easy mode" for multi-GPU training. to do so more effectively is a lot of work.

**Comment by bghira** [comment]
I tested yesterday.

With the current codebase, 24G will just never work. Khoya relies on Adafactor, which I haven't implemented yet.

The dataloader needs adjustments.

**Comment by bghira** [comment]
You might try switching `--use_8bit_adam` to `--use_adafactor_optimizer`

**Comment by bghira** [comment]
good news, with SD 2.x you can now do multi-GPU training thanks to #88 and #92 

the batch size for 2x 24G cards can absolutely work with the same batch size of 1x 48G card - but this is really only effective for SD 2.x right now.

in addition, lower resolutions might work better now on SDXL to reduce vram use, after a couple fixes. but i have not tried.

**Comment by Curlypla** [comment]
It's really incredible! I suppose SDXL support is more complicated given the size of the model, but are you going to try to implement it?

**Comment by bghira** [comment]
the fixes are already there, and it does use drastically lower memory at 512px vs 1024px but i haven't tried to train at eg. 128px to see if it then fits in 24G. i doubt it will, we'd need to fully unload the TEs and VAE, and likely some more deeper look inside the Diffusers u-net code for more inefficiencies.
