### ISSUE TITLE
tensor mismatch error when processing bucketing

### ISSUE THREAD

**Issue by zhuliyi0** [bghira/SimpleTuner#322]
I updated to release 0.9.1, got error for a lot of image (seem like every image) when processing bucketing:

stack expects each tensor to be equal size, but got [3, 856, 1192] at entry 0 and [3, 848, 1200] at entry 1, traceback: Traceback (most recent call last):
  File "/root/SimpleTuner/helpers/caching/vae.py", line 520, in _encode_images_in_batch
    latents = self.encode_images(
  File "/root/SimpleTuner/helpers/caching/vae.py", line 394, in encode_images
    processed_images = torch.stack(uncached_images).to(
RuntimeError: stack expects each tensor to be equal size, but got [3, 856, 1192] at entry 0 and [3, 848, 1200] at entry 1
, file <frame at 0x7fb2d00468f0, file '/root/SimpleTuner/helpers/caching/vae.py', line 609, code _process_futures>, 605, future traceback Traceback (most recent call last):
  File "/root/SimpleTuner/helpers/caching/vae.py", line 520, in _encode_images_in_batch
    latents = self.encode_images(
  File "/root/SimpleTuner/helpers/caching/vae.py", line 394, in encode_images
    processed_images = torch.stack(uncached_images).to(
RuntimeError: stack expects each tensor to be equal size, but got [3, 856, 1192] at entry 0 and [3, 848, 1200] at entry 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/SimpleTuner/helpers/caching/vae.py", line 605, in _process_futures
    future.result()
  File "/root/miniconda3/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/root/miniconda3/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/root/miniconda3/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/SimpleTuner/helpers/caching/vae.py", line 540, in _encode_images_in_batch
    raise Exception(
Exception: Error encoding images ['/root/autodl-tmp/Dataset/arch_aerial_13k/DONE_aerial_rendering_2k/aerial_rendering_huaban_300/27_3273159057.jpg', '/root/autodl-tmp/Dataset/arch_aerial_13k/DONE_arch_rendering_5600/ABUIABACGAAght3s-gUo0ITKjwYwsAk40AY.jpg', '/root/autodl-tmp/Dataset/arch_aerial_13k/DONE_aerial_photo_1300/1_001-Amstel-Tower-by-Powerhouse-Company.jpg', '/root/autodl-tmp/Dataset/arch_aerial_13k/DONE_arch_rendering_5600/ABUIABACGAAg4pvQgAYo0o-7pQUwsAk40wY.jpg']: stack expects each tensor to be equal size, but got [3, 856, 1192] at entry 0 and [3, 848, 1200] at entry 1, traceback: Traceback (most recent call last):
  File "/root/SimpleTuner/helpers/caching/vae.py", line 520, in _encode_images_in_batch
    latents = self.encode_images(
  File "/root/SimpleTuner/helpers/caching/vae.py", line 394, in encode_images
    processed_images = torch.stack(uncached_images).to(
RuntimeError: stack expects each tensor to be equal size, but got [3, 856, 1192] at entry 0 and [3, 848, 1200] at entry 1

I checked the image for this particular error, the size is 1080x770.

any idea please?

**Comment by zhuliyi0** [comment]
was using an slightly older version that was working fine on one of my smaller dataset but error when entering training loop on a different large dataset. So I updated source to latest release and got above.

the command args I was using:

accelerate launch --mixed_precision="bf16" \
	--num_processes="1" \
	--num_machines="1" \
	--dynamo_backend="no" \
/root/SimpleTuner/train_sdxl.py \
	--pretrained_model_name_or_path="/root/autodl-tmp/sd_xl_base_1.0" \
    --allow_tf32 \
	--learning_rate="5e-5" \
	--lr_scheduler="constant_with_warmup" \
	--lr_warmup_steps=500 \
    --snr_gamma=5.0 \
	--seed=2024 \
	--use_8bit_adam \
    --enable_xformers_memory_efficient_attention \
    --gradient_checkpointing \
    --data_backend_config="/root/data_config_13k.json" \
	--max_train_steps="100000" \
	--train_batch="30" \
	--gradient_accumulation_steps="30" \
	--caption_dropout_probability=0.1 \
    --validation_noise_scheduler="euler-a" \
	--validation_guidance="7" \
	--validation_guidance_rescale="0" \
	--validation_steps="1" \
	--validation_resolution="1024" \
	--num_validation_images=1 \
	--user_prompt_library="/root/autodl-tmp/Dataset/13k_prompts.json" \
	--checkpointing_steps="30" \
	--checkpoints_total_limit="2" \
    --tracker_project_name="simpletuner-sdxl_13k-512" \
	--tracker_run_name="b900-5e5" \
    --output_dir="/root/autodl-tmp/simpletunerOutput/13k-sdxl-512-b900-5e5" \
    --report_to="wandb" \

**Comment by bghira** [comment]
this is an issue with the aspect bucketing code with the following configuration:

```
resolution_type=area
crop=false
```

a possible configuration that might avoid the issue:

```
resolution_type=pixel
crop=false
resolution=720
```

which would use edge-length and resize the smaller edge of all images to ~720px.

alternatively,

```
resolution_type=area
crop=true
crop_style=random
crop_aspect=preserve
```

would allow the continued use of area resize, but it will crop samples to the target resolution instead of resizing them.

explanation:

it's something i've been working on - it's a very frustrating issue, to be quite honest.

the reason this occurs is the `area` resolution type resizes images based on pixel area.

when bucketing images,
* the image is EXIF rotated so that we don't accidentally train on incorrect image orientation.
  * side note, fuck cameras that do this, though it's pretty much all of them now
* the new aspect ratio is calculated and used during area resize to target ~1 megapixel
* the new size must be aligned so that it is divisible by 8 or 64.
  * it's better to use 64, since this ensures 1mp = 1024px.
  * if we use a value of 8, then 1mp = 1000px.
* the new aspect ratio is calculated, because (for example) an aspect ratio of 0.69 and 0.71 will result in the same (divisible by 64) image size.
  * recalculating the aspect after these transformations allows us to combine them, which reduces the number of buckets, and allows for higher batch sizes (the number of images in a bucket must >= effective batch size)

during VAE caching,
* the buckets are traversed one at a time.
  * we have to do this because we batch encode images with the VAE, and they must all be the same size (as the error indicates to you)
* this is where things seem to exhibit the first failure mode, because multiple images end up with different sizes in the final batch.
  * but the problem is likely *caused* during the aspect bucket caching operation

it's especially frustrating because i can test it locally with a subset of data, maybe exhibit the issue and resolve it, but then in a much larger dataset with hundreds of thousands of images, this error still occurs.

so it's difficult to put together a dataset that reliably can reproduce **all** of these related issues.

**Comment by bghira** [comment]
just to ensure your dataset is full in alignment with the master branch, please remove the `aspect_*.json` files from the dataset dir and allow the trainer to recreate them.

**Comment by zhuliyi0** [comment]
thanks for the explaination, I see the problem. If allow cropping is a good way to avoid this, how bad would cropping affect quality? Is image size conditioning and crop conditioning used, like in SDXL's original finetuning? 

I tried padding once on a small dataset, seems working fine for my case and some black padding during inference is acceptable for me. So I could manually pad all images to some selected buckets to avoid this issue. This would also eliminate buckets that is smaller than batch size.

will try master branch shortly.

**Comment by bghira** [comment]
cropping while preserving aspect with pixel edge will use the crop conditioning inputs to keep things from damaging the model too much. it's mostly a concern for extremely large training runs where that many crops would potentially harm the weights.

**Comment by zhuliyi0** [comment]
I am trying out master branch. bucket processing is really slow. estimated finish time is 30 min while it only took like 2min before. no error for now.

**Comment by bghira** [comment]
you'll have to run it in debug mode to determine why, because nothing has changed in that part of the codebase
