### ISSUE TITLE
Frontend

### ISSUE THREAD

**Issue by komninoschatzipapas** [bghira/SimpleTuner#396]
I think this project would benefit from having a simple & easy-to-use frontend(web app). I know for a fact that most people creating models on Civit are not very technically savvy and might be intimidated by the command line.

If this fits the direction you wanna go with this project, let me know, and I can create a PR for this. I can also integrate the frontend with Docker so everything can be deployed on Runpod, Vast, etc. in one click.

P.S. I know Gradio is popular amongst Python developers but if I were to do this I would go with JS to have something that looks more visually appealing and user friendly.

**Comment by bghira** [comment]
projects tend to have scopes and intended audiences.

this is an academic project, not something intended for use by end-users. honestly, for the longest time i just didn't even put documentation, because i don't have the bandwidth to field bug reports from users who can't put forth some level of effort into discovering or resolving their issues - and even better, to offer up fixes for it.

when you look at the issue trackers of kohya-ss, bmaltais' gui, derrian distro or any of the number of spin-offs, you begin to understand my position on this one.

to me, adding a GUI will fundamentally alter the intended audience of this project, in the aim of providing a comparable experience to derrian distro or A1111's dreambooth extensions. but both of those tools already exist, and that audience already has support there.

**Comment by komninoschatzipapas** [comment]
That's fair. If you ever decide to go down that route, do let me know. FYI, I found your docs and issue comments to be more insightful than the ones of the other commercial solutions.
