### ISSUE TITLE
SD3 training : Must provide at least one text embed backend in the data backend config file

### ISSUE THREAD

**Issue by scarbain** [bghira/SimpleTuner#452]
Hello, thank you for implementing SD3 training so quickly!

I'm trying to start the LoRA training but I get this error and I don't understand why. 
If dataset_type is not set to "text_embed", I get this error.

**Comment by bghira** [comment]
can you provide the elusive error? :)

**Comment by bghira** [comment]
i have provided a better error message when the embed cache is not found. please let me know if it works for you

**Comment by zer0int** [comment]
I just encountered the same error and have "ugly-fixed" it in factory.py. Apologies to the author for this. ;-)

```
    if not text_embed_backends:
        pass
        #raise ValueError(
        #    "Must provide at least one text embed backend in the data backend config file."
        #)
    if not default_text_embed_backend_id and len(text_embed_backends) > 1:
        raise ValueError(
            "Must provide a default text embed backend in the data backend config file. It requires 'default':true."
        )
    elif not default_text_embed_backend_id:
        logger.warning(
            f"No default text embed was defined, using whatever"#{list(text_embed_backends.keys())[0]} as the default."
        )
        default_text_embed_backend_id = 1#list(text_embed_backends.keys())[0]
    logger.info("Completed loading text embed services.")
```

Then just pass it all in the command-line, with "--override_dataset_config". Seems to work, at least it's in a long "write embeds to disk" loop now, which presumably wouldn't work if there was an error with what to embed. 🙃 

Thank you very much for your work, @bghira - I only had the time to look into ft SD3 today - and finding your repo is a delight. Really appreciate it! 👍 

PS: Not worth rising an issue about, but I also had to comment out "#multiprocessing.set_start_method("fork")" in train_sdxl.py because "fork" is not valid / threw an error; Python 3.10.11

**Comment by bghira** [comment]
maybe you can wrap the multiprocessing change in a try block.

**Comment by bghira** [comment]
it looks like your fix will blow up later as you directed writes to an image backend. i will hhave to clarify the setup in docs later

**Comment by bghira** [comment]
i have updated the relevant error messages to sound more human and relay the user to the dataloader documentation on the github page.
