### ISSUE TITLE
No ability to use multiple captions per image

### ISSUE THREAD

**Issue by AmericanPresidentJimmyCarter** [bghira/SimpleTuner#476]

**Comment by bghira** [comment]
there's some considerations. one reason i like the current setup is because it ends up with causal compression where the identifier being the prompt itself actually causes multiple images sharing one prompt to be combined.

but it's not because the images have the same caption field contents, in a multi-caption scenario just one of the captions might match up. and which one do you index it by?

it would be maybe an optional flag that comes with the caveat of reducing the efficiency of the backend storage

**Comment by bghira** [comment]
see #527 

it needs a multicaption dataset to test with
