### ISSUE TITLE
VAE cache error

### ISSUE THREAD

**Issue by leonary** [bghira/SimpleTuner#643]
```
2024-08-05 18:23:21,124 [ERROR] (__main__) Could not find image path for cache file /root/autodl-tmp/1img/cache/e1abc6fbed735f9b213775b74e49a96b-flux.pt (test_filepath: /root/autodl-tmp/1img/cache/e1abc6fbed735f9b213775b74e49a96b-flux.pt). This occurs when you toggle the value for hashed_filenames without clearing your VAE cache. If it still occurs after clearing the cache, please open an issue: https://github.com/bghira/simpletuner/issues, traceback: Traceback (most recent call last):
  File "/root/autodl-tmp/SimpleTuner/train.py", line 876, in main
    configure_multi_databackend(
  File "/root/autodl-tmp/SimpleTuner/helpers/data_backend/factory.py", line 973, in configure_multi_databackend
    init_backend["vaecache"].discover_unprocessed_files()
  File "/root/autodl-tmp/SimpleTuner/helpers/caching/vae.py", line 360, in discover_unprocessed_files
    existing_image_filenames = {
  File "/root/autodl-tmp/SimpleTuner/helpers/caching/vae.py", line 362, in <setcomp>
    self._image_filename_from_vaecache_filename(cache_file)[0]
  File "/root/autodl-tmp/SimpleTuner/helpers/caching/vae.py", line 160, in _image_filename_from_vaecache_filename
    raise ValueError(
ValueError: Could not find image path for cache file /root/autodl-tmp/1img/cache/e1abc6fbed735f9b213775b74e49a96b-flux.pt (test_filepath: /root/autodl-tmp/1img/cache/e1abc6fbed735f9b213775b74e49a96b-flux.pt). This occurs when you toggle the value for hashed_filenames without clearing your VAE cache. If it still occurs after clearing the cache, please open an issue: https://github.com/bghira/simpletuner/issues
```

All cache files have been deleted but I still got this error, any help would be greatly appreciated.

**Comment by bghira** [comment]
for now you can try --vae_cache_ondemamd

**Comment by leonary** [comment]
> for now you can try --vae_cache_ondemamd

It doesn't seem to work. What's happening now is that the file name used when saving the .pt file doesn't match the new dictionary generated in vae.py. I added some code to print `self.vae_path_to_image_path.items()` in vae.py:

```
/root/autodl-tmp/1img/cache/98872541_p0_master1200_copy47.pt : /root/autodl-tmp/1img/2400_img/98872541_p0_master1200_copy47.jpg
/root/autodl-tmp/1img/cache/98872541_p0_master1200_copy48.pt : /root/autodl-tmp/1img/2400_img/98872541_p0_master1200_copy48.jpg
/root/autodl-tmp/1img/cache/98872541_p0_master1200_copy49.pt : /root/autodl-tmp/1img/2400_img/98872541_p0_master1200_copy49.jpg /root/autodl-tmp/1img/cache/98872541_p0_master1200_copy50.pt : /root/autodl-tmp/1img/2400_img/98872541_p 0_master1200_copy50.jpg 2024-08-05 19:02:30,419 [ERROR] (__main__) Could not find image path for cache file /root/autodl-tmp/1img/cache/e1abc6fbed735f9b213775b74e49a96b-flux.pt (test_filepath: /root/autodl-tmp/1img/cache/e1abc6fbed735f9b213775b74e49a96b-flux.pt). This occurs when you toggle the value for hashed_filenames without clearing your VAE cache. If it still occurs after clearing the cache, please open an issue: https://github.com/bghira/simpletuner/issues, traceback: Traceback (most recent call) : File "/root/autodl-tmp/SimpleTuner/train.py", line 877, in main configure_multi_databackend( File "/root/autodl-tmp/SimpleTuner/helpers/data_backend/factory.py", line 973, in configure_multi_databackend init_backend["vaecache"].discover_unprocessed_files() File "/root/autodl-tmp/SimpleTuner/helpers/caching/vae.py", line 362, in discover_unprocessed_files existing_image_filenames = { File "/root/autodl-tmp/SimpleTuner/helpers/caching/vae.py", line 364, in <setcomp> self._image_filename_from_vaecache_filename(cache_file)[0] File "/root/aut odl-tmp/SimpleTuner/helpers/caching/vae.py", line 162, in _image_filename_from_vaecache_filename raise ValueError( ValueError: Could not find image path for cache file /root/autodl-tmp/1img/cache/e1abc6fbed735f9b213775b74e49a96b-flux.pt (test_filepath: /root/autodl-tmp/1img/cache/e1abc6fbed735f9b213775b74e49a96b-flux occurs.pt). This when you toggle the value for hashed_filenames without clearing your VAE cache. If it still occurs after clearing the cache, please open an issue: https://github.com/bghira/simpletuner/issues
```

**Comment by bghira** [comment]
ok someone on discord identified that this happens when your text and vae cache end up in the same dir. i can look at fixing this later today

**Comment by twri** [comment]
It happens here too, clearing the cache manually and start over works. You just can't reuse the cache between runs. Doesn't matter if you use --vae_cache_ondemamd or not. text and vae cache is in different directories.

**Comment by bghira** [comment]
can either of you share your multidatabackend.json and config.env files? i am unable to easily reproduce this problem locally, and i think maybe there's some issue with relative paths, or subdirectories.

**Comment by twri** [comment]
[config.env.txt](https://github.com/user-attachments/files/16496123/config.env.txt)
[data.json](https://github.com/user-attachments/files/16496126/data.json)

**Comment by bghira** [comment]
background on the problem

old behaviour (before ~may or so):
- trainer did not hash vae cache element filenames
- only supported jpg and png files, not jpeg or webp
- when handling a `cache.pt` file, it is in a different directory (vae_cache_dir) and doesn't directly correlate to image path (instance_data_dir)
- when trainer is given `/cache/image/subdirectory/cache.pt` file it would try to see whether `/data/image/subdirectory/cache.png` or `.jpg` exist - it would map to whichever it finds first

this had some problems:
- only jpg and png could easily be supported without having extensive, slow, and stupid reverse file path checks
- long jpg/png filenames would sometimes translate into a longer pt path, and emit OSError when filename is too long
- just kinda felt bad and wrong

the current behaviour:
- trainer tries not to hash VAE elements that were created by the older version of the trainer, so that users didn't have to re-cache millions of images just because I had to solve a hard problem
- at startup, every cache file is mapped to its image equivalent, and this mapping is stored inside the sampler object for quick lookups
- two lists are maintained: cache-to-image and image-to-cache, because looking up values was slower than keys, and the memory overhead is who cares, even for millions of samples

unfortunately, this also introduced some problems:
- the backwards compatibility code had an issue that I looked into and resolved yesterday; the config value `hash_filenames` was inferred, but not correctly registered into the backend
  - this really only impacted older datasets that were in use since before May. removing the metadata / aspect lists / vae cache allows this one to work, after re-caching.
  - adding `hash_filenames=true` to the dataloader config for this dataset also worked around the problem
- sporadically, the cache filename is not correctly mapped back to its source image. this is the current issue we are looking at.

**Comment by bghira** [comment]
alright, i have resolved this - it just looks like the filename hasn't hashed during the check. it should now be a bit faster and run more reliably, especially if you have image files with the same stem but different extensions, eg. `foo.png`, `foo.webp`, `foo.jpg`

**Comment by bghira** [comment]
anyone from an old version / dataset who runs into this issue and your cache **does not have hashed filenames**, setting `hash_filenames=false` in your data backend config will resolve it
