### ISSUE TITLE
Please readd support for Prodigy

### ISSUE THREAD

**Issue by axel578** [bghira/SimpleTuner#897]
Even if there is miscalculation or else, prodigy is extremely good and fast and efficient and doesnt produce overcontrasted images like other optimizer.

ALso if I try to train on white background images, it still end up producing images with black background or weird effects, I tried a lot of settings to avoid it without success, I can't train a lora with background staying white using any preset or settings.

**Comment by bghira** [comment]
sorry, the optim has nothing to do with those issues

**Comment by bghira** [comment]
prodigy is just an optimiser but it doesn't support the correct precision levels. i strongly disagree that it's any better than any other optimiser. as you stated you have dataset issues you should figure out first - it's probable that the issue lies there, and not in which optim you are using.

the white vs black background is an issue with the model's noise schedule. this isn't anything that can be changed through simpletuner. see [common diffusion noise schedules and sample steps are flawed](https://arxiv.org/abs/2305.08891).
